name: CI

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate data
      run: echo Hello, world!

